name: Portfolio Deployment

on:
  push:
    branches:
      - main
      - test

jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - name: Print event details
        run: |
          echo "The job was automatically triggered by a ${{ github.event_name }} event."
          echo "This job is now running on a ${{ runner.os }} server hosted by GitHub!"
          echo "The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."

      - name: Check out repository code
        uses: actions/checkout@v3

      - name: Repository cloned confirmation
        run: echo "The ${{ github.repository }} repository has been cloned to the runner."
      
      - name: List files in the repository
        run: |
          ls ${{ github.workspace }}
      
      - name: Print job status
        run: echo "This job's status is ${{ job.status }}."

